name: zabbix-azure-pipeline

# Get variables
variables:
- group: Send-parameters

# this pipeline will be triggered by another pipeline
resources:
  pipelines:
  - pipeline: deploy_worldcup2026countdown   # Name of the pipeline resource
    source: azure-pipelines.yml # Name of the pipeline referenced by the pipeline resource
    #project: Trigger-Pipeline-From-Another-Pipeline # Required only if the source pipeline is in another project
    trigger: true # enable the trigger

# Specify the agent pool
pool:
  name: zabbix

# Define the pipeline steps
jobs:    

  - job: pipeline_status_to_zabbix
    displayName: Send the pipeline build status to Zabbix
    steps:
      - script: |
          # Get the pipeline status
          status = "$(Pipeline.Status)"

          # Send the pipeline status to Zabbix using zabbix_sender
          zabbix_sender -z $(zabbixhost) -s '$(zabbixserver)' -k $(zabbixkey) -o "$(curl --header 'Authorization:Basic $(PAT)=' --get '$(pipelineurl)$top=1')"
