# Get variables
variables:
- group: Send-parameters

# Configure the pipeline
trigger: none

# Specify the agent pool
pool:
  name: zabbix

# Define the pipeline steps
jobs:    

  - job: pipeline_status_to_zabbix
    displayName: Send the pipeline build status to Zabbix
    steps:
      - script: |
          # Get the pipeline status
          status = "$(Pipeline.Status)"

          # Send the pipeline status to Zabbix using zabbix_sender
          zabbix_sender -z $(zabbixhost) -s '$(zabbixserver)' -k $(zabbixkey) -o "$(curl --header 'Authorization:Basic $(PAT)=' --get '$(pipelineurl)$top=1')"