# Get variables
variables:
- group: Send-parameters

# this pipeline will be triggered by another pipeline
resources:
  pipelines:
  - pipeline: worldcup2026countdown # Name of the pipeline resource
    source: zingaya.worldcup2026 # Name of the pipeline referenced by the pipeline resource
    trigger: true # enable the trigger
    
# Specify the agent pool
pool:
  name: zabbix

# Define the pipeline steps
jobs:    

  - job: pipeline_status_to_zabbix
    displayName: Send the pipeline build status to Zabbix
    steps:
      - script: |
          # Send the pipeline status to Zabbix using zabbix_sender
          zabbix_sender -z $(zabbixserver) -s '$(zabbixhost)' -k $(zabbixkey) -o "$(curl --header "Authorization:Basic $(PAT)=" --get '$(pipelineurl)$top=1')"
